#!/bin/bash
git add --all
if [[ $? -ne 0 ]]
then
	echo "$(tput setaf 1)"'ERROR, exiting'"$(tput sgr 0)"
	exit 1
fi
git commit -m 'Update'
then
	echo "$(tput setaf 1)"'ERROR, exiting'"$(tput sgr 0)"
	exit 1
fi
git push -u origin master
then
	echo "$(tput setaf 1)"'ERROR, exiting'"$(tput sgr 0)"
	exit 1
fi
exit 0
